# Generated by Django 2.2.2 on 2020-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200203_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='factory',
            field=models.CharField(max_length=200, null=True, verbose_name='Производитель'),
        ),
    ]
