# Generated by Django 2.2.2 on 2020-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200203_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='batch_number',
            field=models.CharField(max_length=256, null=True, verbose_name='Партия'),
        ),
    ]
