# Generated by Django 2.2.2 on 2020-02-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200206_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='scancode',
            field=models.CharField(max_length=20, null=True, verbose_name='Штрихкод'),
        ),
    ]
